### ISSUE TITLE
Can not find default.json

### ISSUE THREAD

**Issue by hkatzdev** [eankeen/fox-suite#66]
`[Error: ENOENT: no such file or directory, open '/home/hkatzdev/hackagotchi-automator/node_modules/.pnpm/fox-utils@1.0.1/node_modules/fox-utils/src/default.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/hkatzdev/hackagotchi-automator/node_modules/.pnpm/fox-utils@1.0.1/node_modules/fox-utils/src/default.json'
}
`

**Comment by eankeen** [comment]
haii i'll take a look in into this

**Comment by eankeen** [comment]
hai,

this was fixed in `1.0.4` :)
i'm' still working on getting a few bugs and in consistencies out - i admit the `1.0.0` version designation may have been a tad premature
